services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db:
    driver: local
